# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

ModuleNotFoundError: No module named 'pandas'

In [2]:
tf.__version__

NameError: name 'tf' is not defined

## Part 1 - Data Preprocessing
#### Take about 70% work of a DataScientist

### Importing the dataset

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


In [10]:
dataset.isna().count()

RowNumber          10000
CustomerId         10000
Surname            10000
CreditScore        10000
Geography          10000
Gender             10000
Age                10000
Tenure             10000
Balance            10000
NumOfProducts      10000
HasCrCard          10000
IsActiveMember     10000
EstimatedSalary    10000
Exited             10000
dtype: int64

### Encoding categorical data

Label Encoding the "Gender" column

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [13]:
#encoded is 0=female, 1=male
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column
No order relationship between France, Spain, Germany that is why we can not encode to 1,2,3

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling
#### Absolutely compulsory in DeepLearning, apply to all features to both training and test set



In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)#fitted to training set to avoid information leakage
X_test = sc.transform(X_test)

## Part 2 - Building the ANN(Brain)

### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer
#### There is no rule of thumb of how many Neurons we want, we have to experiment with different hyperparameters.

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'  ))#relu is rectifier activation function

W1024 12:51:05.203107 27284 deprecation.py:506] From C:\Users\catan\.conda\envs\catanEnv\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


### Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'  ))

### Adding the output layer

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'  ))#output neuron=1 coz it binary, sigmoid activation for output of probability of 1 or 0 

## Part 3 - Training the ANN(Brain will learn)

### Compiling the ANN

In [23]:
ann.compile(optimizer='adam', loss ='binary_crossentropy', metrics = ['accuracy'] )
#adam,perform stochastic gradient descent which update weight to reduce loss error between prediction and real result.
#binary_crossentropy,loss function for binary classification, activation should be softmax
#categorical_crossentropy,for function for non-binary classification, ex 3 category. activation should softmax not sigmoid
#check regrssion sample, for regression output

### Training the ANN on the Training set

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#batch_size = 32 default value
#epochs=100, neural network is certainly need to train in a certain amount of epochs to able to learn about the data and to improve accuracy overtime

W1024 13:15:23.810964 27284 deprecation.py:323] From C:\Users\catan\.conda\envs\catanEnv\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.5401 - acc: 0.7714
Epoch 2/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4598 - acc: 0.8055
Epoch 3/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4377 - acc: 0.8106
Epoch 4/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4267 - acc: 0.8165
Epoch 5/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4196 - acc: 0.8206
Epoch 6/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4135 - acc: 0.8217
Epoch 7/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4080 - acc: 0.8238
Epoch 8/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4023 - acc: 0.8291
Epoch 9/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3964 - acc: 0.8335
Epoch 10/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.3903 - a

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [30]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 6000, 2, 1, 1, 50000]]))) #result in probability

[[0.02121088]]


In [31]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 6000, 2, 1, 1, 50000]])) > 0.5)

[[False]]






Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [33]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 197  208]]


0.8625